name: Format Code with Prettier

permissions:
  contents: write

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npx prettier --write .

      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Áp dụng định dạng tự động'
          branch: ${{ github.head_ref }}
